### ISSUE TITLE
Deezer Connect

### ISSUE THREAD

**Issue by Cygn** [Valentin271/DeezerKodi#24]
Hi there!
First, thx for your work - much appreciated. 

Deezer has finally introduced a "connect" feature. But basically it's more a remote controller: from a mobile app, you can control a webplayer or another mobile app connected to your account. https://en.deezercommunity.com/product-updates/let-s-take-control-of-your-sound-with-deezer-connect-75531

Anyway, it would be awesome to have it in Kodi :)

+

**Comment by david-morris** [comment]
I [posted a comment](https://en.deezercommunity.com/product-updates/let-s-take-control-of-your-sound-with-deezer-connect-75531/index4.html?postid=1087#post1087) on that thread after I didn't see Connect in the REST API.  Unfortunately, the comments for that release notice are swamped with flame because people are comparing Deezer Connect with Spotify Connect, a much more mature technology.

**Comment by Valentin271** [comment]
I'm afraid this won't be possible.

There is no sign of Deezer connect in the API. The feature doesn't work for me so reverse engineering it is not really an option.
Moreover, I don't even think this is implemented via the API but instead via some sort of websocket.

The feature is rather new and will maybe evolve to allow third parties using it. Might look into it in the future.
